# Generated by Django 4.0.1 on 2022-01-05 12:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HojaMtn25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoja', models.CharField(editable=False, max_length=50, verbose_name='Número de hoja')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Localización')),
            ],
            options={
                'verbose_name': 'hoja MTN25',
                'verbose_name_plural': '\tHojas MTN25',
                'ordering': ['hoja'],
            },
        ),
        migrations.CreateModel(
            name='HojaMtn50',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoja', models.CharField(max_length=50, verbose_name='Número de hoja')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Localización')),
            ],
            options={
                'verbose_name': 'hoja MTN50',
                'verbose_name_plural': '\t\tHojas MTN50',
                'ordering': ['hoja'],
            },
        ),
    ]
