# Generated by Django 4.0.1 on 2022-11-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojasmtn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojamtn25',
            name='hoja',
            field=models.CharField(editable=False, max_length=128, verbose_name='Número de hoja'),
        ),
        migrations.AlterField(
            model_name='hojamtn25',
            name='nombre',
            field=models.CharField(max_length=128, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='hojamtn50',
            name='hoja',
            field=models.CharField(max_length=128, verbose_name='Número de hoja'),
        ),
        migrations.AlterField(
            model_name='hojamtn50',
            name='nombre',
            field=models.CharField(max_length=128, verbose_name='Nombre'),
        ),
    ]
