# Generated by Django 4.0.1 on 2022-01-05 11:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComAutonoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Localización')),
            ],
            options={
                'verbose_name': 'comunidad autónoma',
                'verbose_name_plural': '\t\t\t\tComunidades autónomas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Isla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Localización')),
                ('com_autonoma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidadmin.comautonoma', verbose_name='Comunidad autónoma')),
            ],
            options={
                'verbose_name': 'isla',
                'verbose_name_plural': '\t\tIslas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=44, verbose_name='Nombre')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Localización')),
            ],
            options={
                'verbose_name': 'país',
                'verbose_name_plural': '\t\t\t\t\tPaíses',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Localización')),
                ('com_autonoma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidadmin.comautonoma', verbose_name='Comunidad autónoma')),
            ],
            options={
                'verbose_name': 'provincia',
                'verbose_name_plural': '\t\t\tProvincias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Localización')),
                ('com_autonoma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidadmin.comautonoma', verbose_name='Comunidad autónoma')),
                ('isla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidadmin.isla', verbose_name='Isla')),
                ('provincia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidadmin.provincia', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'municipio',
                'verbose_name_plural': '\tMunicipios',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='isla',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidadmin.provincia', verbose_name='Provincia'),
        ),
    ]
