# Generated by Django 4.0.1 on 2022-11-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidadmin', '0002_isla_unidadmin_i_com_aut_cc7b99_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['nombre'], 'verbose_name': 'lol', 'verbose_name_plural': '\t\t\t\t\tPaíses'},
        ),
    ]
