# Generated by Django 4.0.1 on 2022-11-24 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidadmin', '0003_alter_pais_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['nombre'], 'verbose_name': 'país', 'verbose_name_plural': '\t\t\t\t\tPaíses'},
        ),
    ]
