# Generated by Django 4.0.1 on 2022-11-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidadmin', '0004_alter_pais_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=128, verbose_name='Nombre'),
        ),
    ]
