# Generated by Django 4.0.1 on 2022-11-24 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidadmin', '0005_alter_pais_nombre'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='isla',
            name='unidadmin_i_com_aut_cc7b99_idx',
        ),
    ]
