# Generated by Django 4.0.1 on 2022-11-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidadmin', '0006_remove_isla_unidadmin_i_com_aut_cc7b99_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='municipio',
            name='unidadmin_m_com_aut_164650_idx',
        ),
    ]
