# Generated by Django 4.0.1 on 2022-11-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidadmin', '0007_remove_municipio_unidadmin_m_com_aut_164650_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='municipio',
            name='unidadmin_m_provinc_604a99_idx',
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['provincia', 'isla'], name='unidadmin_m_provinc_57a6aa_idx'),
        ),
    ]
