# Generated by Django 4.0.1 on 2022-01-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0002_alter_puntoobs_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoobs',
            name='num_fotos',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
