# Generated by Django 4.0.1 on 2022-01-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0003_puntoobs_num_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoobs',
            name='tiene_descripcion',
            field=models.BooleanField(default=True, editable=False),
            preserve_default=False,
        ),
    ]
