# Generated by Django 4.0.1 on 2022-01-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0004_puntoobs_tiene_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntoobs',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción'),
        ),
    ]
