# Generated by Django 4.0.1 on 2022-01-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0005_alter_puntoobs_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='incertidumbre_gradiente',
            field=models.FloatField(blank=True, null=True, verbose_name='Incertidumbre en la medida del gradiente [μGal]'),
        ),
    ]
