# Generated by Django 4.0.1 on 2022-01-10 14:22

from django.db import migrations, models
import gravimetria.auxiliary_functions


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0006_observacion_incertidumbre_gradiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='id_estacion',
            field=models.CharField(db_index=True, help_text='Identificador de la estación siguiendo el formato PROV_MUNI', max_length=16, unique=True, verbose_name='ID estación'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='nombre',
            field=models.CharField(db_index=True, help_text='Denominación descriptiva de la estación', max_length=128, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='red_secundaria',
            field=models.ManyToManyField(blank=True, db_index=True, help_text='Otras redes a las que pertenece o con las que enlaza la estación', limit_choices_to=models.Q(('nombre', 'REGA'), _negated=True), related_name='red_secundaria', to='gravimetria.Red', verbose_name='Redes secundarias'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='dispersion',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Dispersión entre sets [μGal]'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='fichero_project',
            field=models.FileField(blank=True, db_index=True, help_text='Se debe guardar y continuar para que rellene             automaticamente los campos asociados', max_length=200, null=True, upload_to=gravimetria.auxiliary_functions.ruta_ficheros_g, verbose_name='Fichero project'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='incertidumbre_total',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Incertidumbre total [μGal]'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='operador_observacion',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='operador_observacion', to='gravimetria.Operador', verbose_name='Operadores que realizaron la observación'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='publicable',
            field=models.BooleanField(db_index=True, verbose_name='Publicable'),
        ),
        migrations.AlterField(
            model_name='puntoobs',
            name='estado_senal',
            field=models.IntegerField(choices=[(1, 'Buen estado'), (2, 'Mal estado'), (3, 'Desconocido')], db_index=True, verbose_name='Estado de la señal'),
        ),
        migrations.AlterField(
            model_name='puntoobs',
            name='id_punto_obs',
            field=models.CharField(db_index=True, help_text='AA, BB... para puntos no monumentalizados; P1, Pn... para pilares', max_length=3, verbose_name='ID Punto de observación'),
        ),
        migrations.AlterField(
            model_name='puntoobs',
            name='num_fotos',
            field=models.IntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='puntoobs',
            name='tipo_acceso',
            field=models.IntegerField(choices=[(1, 'Público'), (2, 'Privado'), (3, 'Desconocido')], db_index=True, verbose_name='Tipo de acceso'),
        ),
        migrations.AlterField(
            model_name='puntoobs',
            name='tipo_senal',
            field=models.IntegerField(choices=[(1, 'Pilar'), (2, 'Clavo'), (3, 'Marca'), (4, 'Sin señalizar'), (5, 'Desconocido')], db_index=True, verbose_name='Tipo de señalización'),
        ),
    ]
