# Generated by Django 4.0.1 on 2022-01-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0007_alter_estacion_id_estacion_alter_estacion_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gravimetro',
            name='ultimo_mantenimiento',
        ),
    ]
