# Generated by Django 4.0.1 on 2022-01-30 15:09

from django.db import migrations, models
import django.db.models.deletion
import gravimetria.auxiliary_functions


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0008_remove_gravimetro_ultimo_mantenimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estacion',
            options={'ordering': ['id_estacion'], 'verbose_name': 'estación', 'verbose_name_plural': '\t\t\t\t\t\t\t\tEstaciones'},
        ),
        migrations.AlterModelOptions(
            name='gravimetro',
            options={'ordering': ['institucion', 'modelo', 'numero_serie'], 'verbose_name': 'gravímetro', 'verbose_name_plural': '\t\t\tGravímetros'},
        ),
        migrations.AlterModelOptions(
            name='institucion',
            options={'ordering': ['nombre'], 'verbose_name': 'institución', 'verbose_name_plural': '\t\t\t\t\tInstituciones'},
        ),
        migrations.AlterModelOptions(
            name='observacion',
            options={'ordering': ['estacion', 'punto_obs', '-fecha_observacion'], 'verbose_name': 'observación', 'verbose_name_plural': '\t\t\t\t\t\tObservaciones'},
        ),
        migrations.AlterModelOptions(
            name='puntoobs',
            options={'ordering': ['estacion', 'id_punto_obs'], 'verbose_name': 'punto de observación', 'verbose_name_plural': '\t\t\t\t\t\t\tPuntos de observación'},
        ),
        migrations.AlterModelOptions(
            name='red',
            options={'ordering': ['nombre'], 'verbose_name': 'red', 'verbose_name_plural': '\t\t\t\tRedes'},
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.IntegerField(choices=[(1, 'General'), (2, 'Calibración del láser'), (3, 'Calibración del reloj'), (4, 'Comparación'), (5, 'Reparación'), (6, 'Otro')], verbose_name='Tipo de operación realizada')),
                ('fecha_mantenimiento', models.DateField(verbose_name='Fecha')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fichero_mantenimiento', models.FileField(blank=True, max_length=200, null=True, upload_to=gravimetria.auxiliary_functions.ruta_mantenimiento, verbose_name='Fichero')),
                ('gravímetro', models.ForeignKey(help_text='Instrumento sobre el que se ha realizado la operación de mantenimiento', on_delete=django.db.models.deletion.CASCADE, to='gravimetria.gravimetro', verbose_name='Gravímetro')),
            ],
        ),
    ]
