# Generated by Django 4.0.1 on 2022-01-30 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0010_alter_mantenimiento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={'ordering': ['gravimetro', '-fecha_mantenimiento'], 'verbose_name': 'tarea de mantenimiento', 'verbose_name_plural': '\t\tMantenimiento'},
        ),
        migrations.RemoveField(
            model_name='observacion',
            name='observaciones',
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='gravimetro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gravimetria.gravimetro', verbose_name='Gravímetro'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo_mantenimiento',
            field=models.IntegerField(choices=[(1, 'Mantenimiento periódico'), (2, 'Calibración del láser'), (3, 'Calibración del reloj'), (4, 'Comparación'), (5, 'Reparación'), (6, 'Otra')], verbose_name='Tipo de tarea realizada'),
        ),
    ]
