# Generated by Django 4.0.1 on 2022-02-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0014_rename_incertidumbre_instrumental_observacion_incertidumbre_sistematica'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['gravimetro'], name='gravimetria_gravime_2c23c2_idx'),
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['tipo_mantenimiento'], name='gravimetria_tipo_ma_239b99_idx'),
        ),
    ]
