# Generated by Django 4.0.1 on 2022-02-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0015_mantenimiento_gravimetria_gravime_2c23c2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='id_estacion',
            field=models.CharField(help_text='Identificador de la estación siguiendo el formato PROV_MUNI', max_length=16, unique=True, verbose_name='ID estación'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='nombre',
            field=models.CharField(help_text='Denominación descriptiva de la estación', max_length=128, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='red_secundaria',
            field=models.ManyToManyField(blank=True, help_text='Otras redes a las que pertenece o con las que enlaza la estación', limit_choices_to=models.Q(('nombre', 'REGA'), _negated=True), related_name='red_secundaria', to='gravimetria.Red', verbose_name='Redes secundarias'),
        ),
    ]
