# Generated by Django 4.0.1 on 2022-02-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0016_alter_estacion_id_estacion_alter_estacion_nombre_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='estacion',
            index=models.Index(fields=['red_primaria'], name='gravimetria_red_pri_9132d0_idx'),
        ),
        migrations.AddIndex(
            model_name='estacion',
            index=models.Index(fields=['com_autonoma'], name='gravimetria_com_aut_c7b853_idx'),
        ),
        migrations.AddIndex(
            model_name='estacion',
            index=models.Index(fields=['provincia'], name='gravimetria_provinc_5c31ab_idx'),
        ),
        migrations.AddIndex(
            model_name='estacion',
            index=models.Index(fields=['isla'], name='gravimetria_isla_id_1ad074_idx'),
        ),
        migrations.AddIndex(
            model_name='estacion',
            index=models.Index(fields=['municipio'], name='gravimetria_municip_67012c_idx'),
        ),
        migrations.AddIndex(
            model_name='estacion',
            index=models.Index(fields=['com_autonoma', 'provincia', 'isla', 'municipio'], name='gravimetria_com_aut_8a2270_idx'),
        ),
    ]
