# Generated by Django 4.0.1 on 2022-02-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0017_estacion_gravimetria_red_pri_9132d0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntoobs',
            name='estado_senal',
            field=models.IntegerField(choices=[(1, 'Buen estado'), (2, 'Mal estado'), (3, 'Desconocido')], verbose_name='Estado de la señal'),
        ),
        migrations.AlterField(
            model_name='puntoobs',
            name='id_punto_obs',
            field=models.CharField(help_text='AA, BB... para puntos no monumentalizados; P1, Pn... para pilares', max_length=3, verbose_name='ID Punto de observación'),
        ),
        migrations.AlterField(
            model_name='puntoobs',
            name='num_fotos',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='puntoobs',
            name='tipo_acceso',
            field=models.IntegerField(choices=[(1, 'Público'), (2, 'Privado'), (3, 'Desconocido')], verbose_name='Tipo de acceso'),
        ),
        migrations.AlterField(
            model_name='puntoobs',
            name='tipo_senal',
            field=models.IntegerField(choices=[(1, 'Pilar'), (2, 'Clavo'), (3, 'Marca'), (4, 'Sin señalizar'), (5, 'Desconocido')], verbose_name='Tipo de señalización'),
        ),
        migrations.AddIndex(
            model_name='estacion',
            index=models.Index(fields=['com_autonoma', 'provincia', 'isla'], name='gravimetria_com_aut_c1f3ac_idx'),
        ),
        migrations.AddIndex(
            model_name='estacion',
            index=models.Index(fields=['com_autonoma', 'provincia', 'municipio'], name='gravimetria_com_aut_4d4542_idx'),
        ),
        migrations.AddIndex(
            model_name='estacion',
            index=models.Index(fields=['com_autonoma', 'isla', 'municipio'], name='gravimetria_com_aut_bb33a9_idx'),
        ),
        migrations.AddIndex(
            model_name='estacion',
            index=models.Index(fields=['provincia', 'isla', 'municipio'], name='gravimetria_provinc_6fd101_idx'),
        ),
        migrations.AddIndex(
            model_name='estacion',
            index=models.Index(fields=['com_autonoma', 'provincia'], name='gravimetria_com_aut_aab528_idx'),
        ),
        migrations.AddIndex(
            model_name='estacion',
            index=models.Index(fields=['com_autonoma', 'isla'], name='gravimetria_com_aut_aed226_idx'),
        ),
        migrations.AddIndex(
            model_name='estacion',
            index=models.Index(fields=['com_autonoma', 'municipio'], name='gravimetria_com_aut_81fa5f_idx'),
        ),
        migrations.AddIndex(
            model_name='estacion',
            index=models.Index(fields=['provincia', 'isla'], name='gravimetria_provinc_f82965_idx'),
        ),
        migrations.AddIndex(
            model_name='estacion',
            index=models.Index(fields=['provincia', 'municipio'], name='gravimetria_provinc_9b3b89_idx'),
        ),
        migrations.AddIndex(
            model_name='estacion',
            index=models.Index(fields=['isla', 'municipio'], name='gravimetria_isla_id_a659f7_idx'),
        ),
        migrations.AddIndex(
            model_name='puntoobs',
            index=models.Index(fields=['tipo_senal'], name='gravimetria_tipo_se_92b80e_idx'),
        ),
        migrations.AddIndex(
            model_name='puntoobs',
            index=models.Index(fields=['estado_senal'], name='gravimetria_estado__56e42e_idx'),
        ),
        migrations.AddIndex(
            model_name='puntoobs',
            index=models.Index(fields=['tipo_acceso'], name='gravimetria_tipo_ac_a9585d_idx'),
        ),
        migrations.AddIndex(
            model_name='puntoobs',
            index=models.Index(fields=['tiene_descripcion'], name='gravimetria_tiene_d_35a099_idx'),
        ),
        migrations.AddIndex(
            model_name='puntoobs',
            index=models.Index(fields=['num_fotos'], name='gravimetria_num_fot_7e668c_idx'),
        ),
        migrations.AddIndex(
            model_name='puntoobs',
            index=models.Index(fields=['estacion'], name='gravimetria_estacio_5615be_idx'),
        ),
    ]
