# Generated by Django 4.0.1 on 2022-02-02 19:44

from django.db import migrations, models
import gravimetria.auxiliary_functions


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0018_alter_puntoobs_estado_senal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacion',
            name='dispersion',
            field=models.FloatField(blank=True, null=True, verbose_name='Dispersión entre sets [μGal]'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='fichero_project',
            field=models.FileField(blank=True, help_text='Se debe guardar y continuar para que rellene             automaticamente los campos asociados', max_length=200, null=True, upload_to=gravimetria.auxiliary_functions.ruta_ficheros_g, verbose_name='Fichero project'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='incertidumbre_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Incertidumbre total [μGal]'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='operador_observacion',
            field=models.ManyToManyField(blank=True, related_name='operador_observacion', to='gravimetria.Operador', verbose_name='Operadores que realizaron la observación'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='publicable',
            field=models.BooleanField(verbose_name='Publicable'),
        ),
    ]
