# Generated by Django 4.0.1 on 2022-02-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0020_gravimetro_gravimetria_tipo_gr_50d6c2_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='puntoobs',
            constraint=models.CheckConstraint(check=models.Q(('latitud__lte', 90)), name='latitud_lte_90'),
        ),
    ]
