# Generated by Django 4.0.1 on 2022-02-02 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0021_puntoobs_latitud_lte_90'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='puntoobs',
            name='latitud_lte_90',
        ),
    ]
