# Generated by Django 4.0.1 on 2022-02-04 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0022_remove_puntoobs_latitud_lte_90'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntoobs',
            name='latitud',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=90, message='Introduzca un valor entre 90º y -90º'), django.core.validators.MinValueValidator(limit_value=-90, message='Introduzca un valor entre 90º y -90º')], verbose_name='Latitud [º]'),
        ),
        migrations.AlterField(
            model_name='puntoobs',
            name='longitud',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=180, message='Introduzca un valor entre 180º y -180º'), django.core.validators.MinValueValidator(limit_value=-180, message='Introduzca un valor entre 180º y -180º')], verbose_name='Longitud [º]'),
        ),
    ]
