# Generated by Django 4.0.1 on 2022-02-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0024_observacion_tipo_gradiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacion',
            name='tipo_gradiente',
            field=models.IntegerField(blank=True, choices=[(1, 'Teórico'), (2, 'Observado')], null=True, verbose_name='Tipo de gradiente empleado'),
        ),
    ]
