# Generated by Django 4.0.1 on 2022-02-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0027_alter_observacion_observaciones_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacion',
            name='observaciones_procesado',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observaciones relativas al procesado'),
        ),
    ]
