# Generated by Django 4.0.1 on 2022-03-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0028_alter_observacion_observaciones_procesado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacion',
            name='observaciones_medida',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones relativas a la medida'),
        ),
    ]
