# Generated by Django 4.0.1 on 2022-03-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0029_alter_observacion_observaciones_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='frecuencia_reloj',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observacion',
            name='laser_blue_wlength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observacion',
            name='laser_dpeak_volt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observacion',
            name='laser_dpeak_wlength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observacion',
            name='laser_epeak_volt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observacion',
            name='laser_epeak_wlength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observacion',
            name='laser_fpeak_volt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observacion',
            name='laser_fpeak_wlength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observacion',
            name='laser_gpeak_volt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observacion',
            name='laser_gpeak_wlength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observacion',
            name='laser_hpeak_volt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observacion',
            name='laser_hpeak_wlength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observacion',
            name='laser_ipeak_volt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observacion',
            name='laser_ipeak_wlength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observacion',
            name='laser_jpeak_volt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observacion',
            name='laser_jpeak_wlength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observacion',
            name='laser_red_wlength',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
