# Generated by Django 4.0.1 on 2022-03-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0030_observacion_frecuencia_reloj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='resenable',
            field=models.BooleanField(default=False, help_text='Marcar si se desea emplear en la reseña', verbose_name='Reseña'),
            preserve_default=False,
        ),
    ]
