# Generated by Django 4.0.1 on 2022-04-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0031_observacion_resenable'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='gravedad_observacion',
            field=models.FloatField(blank=True, null=True, verbose_name='Gravedad a la altura de observación [μGal]'),
        ),
        migrations.AddField(
            model_name='observacion',
            name='gravedad_procesada',
            field=models.FloatField(blank=True, null=True, verbose_name='Gravedad a la altura de procesado [μGal]'),
        ),
    ]
