# Generated by Django 4.0.1 on 2022-04-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0032_observacion_gravedad_observacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observacion',
            name='gravedad',
        ),
    ]
