# Generated by Django 4.0.1 on 2022-04-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0033_remove_observacion_gravedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='gravedad_observada',
            field=models.FloatField(blank=True, null=True, verbose_name='Gravedad a la altura de observación [μGal]'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='gravedad_procesada',
            field=models.FloatField(blank=True, help_text='Valor de la gravedad a la altura de procesado', null=True, verbose_name='Gravedad procesada [μGal]'),
        ),
    ]
