# Generated by Django 4.0.1 on 2022-04-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0034_observacion_gravedad_observada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacion',
            name='gravedad_observada',
            field=models.FloatField(blank=True, help_text='Valor de la gravedad a la altura de observación', null=True, verbose_name='Gravedad observada [μGal]'),
        ),
    ]
