# Generated by Django 4.0.1 on 2022-04-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0035_alter_observacion_gravedad_observada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observacion',
            name='gravedad_observacion',
        ),
    ]
