# Generated by Django 4.0.1 on 2022-04-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0036_remove_observacion_gravedad_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacion',
            name='gravedad_observada',
            field=models.FloatField(blank=True, null=True, verbose_name='Gravedad observada [μGal]'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='gravedad_procesada',
            field=models.FloatField(blank=True, null=True, verbose_name='Gravedad procesada [μGal]'),
        ),
    ]
