# Generated by Django 4.0.1 on 2022-05-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0038_alter_mantenimiento_tipo_mantenimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={'ordering': ['gravimetro', '-fecha_mantenimiento', 'tipo_mantenimiento'], 'verbose_name': 'tarea de mantenimiento', 'verbose_name_plural': '\t\tMantenimiento'},
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo_mantenimiento',
            field=models.IntegerField(choices=[(1, 'Cambio de la correa'), (2, 'Cambio de la bomba iónica'), (3, 'Mantenimiento del láser'), (4, 'Calibración del láser'), (5, 'Calibración del reloj'), (6, 'Electrónica'), (7, 'Comparación'), (8, 'Otra')], verbose_name='Tipo de tarea realizada'),
        ),
    ]
