# Generated by Django 4.0.1 on 2022-07-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0040_alter_gravimetro_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gravimetro',
            name='modelo',
            field=models.IntegerField(choices=[(1, 'A10'), (2, 'FG5'), (3, 'LRG'), (4, 'gPhone'), (5, 'gPhoneX'), (6, 'CG5'), (7, 'B'), (8, 'LRD')], verbose_name='Modelo'),
        ),
    ]
