# Generated by Django 4.0.1 on 2022-08-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0044_alter_observacion_observaciones_medida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacion',
            name='resenable',
            field=models.BooleanField(help_text='Marcar si se desea emplear en la reseña en vez de otras observaciones', verbose_name='Reseña'),
        ),
    ]
