# Generated by Django 4.0.1 on 2022-11-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0045_alter_observacion_resenable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gravimetro',
            name='numero_serie',
            field=models.CharField(max_length=8, verbose_name='Número de serie'),
        ),
    ]
