# Generated by Django 4.0.1 on 2022-11-25 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0046_alter_gravimetro_numero_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gravimetro',
            name='institucion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='gravimetria.institucion', verbose_name='Institución'),
        ),
    ]
