# Generated by Django 4.0.1 on 2022-11-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0047_alter_gravimetro_institucion'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mantenimiento',
            constraint=models.UniqueConstraint(fields=('gravimetro', 'tipo_mantenimiento', 'fecha_mantenimiento'), name='unique_mantenimiento'),
        ),
    ]
