# Generated by Django 4.0.1 on 2022-11-28 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0048_mantenimiento_unique_mantenimiento'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gravimetro',
            unique_together=set(),
        ),
    ]
