# Generated by Django 4.0.1 on 2022-11-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0051_remove_estacion_gravimetria_com_aut_c7b853_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='estacion',
            index=models.Index(fields=['id_estacion'], name='gravimetria_id_esta_ee29ce_idx'),
        ),
    ]
