# Generated by Django 4.0.1 on 2022-11-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0052_estacion_gravimetria_id_esta_ee29ce_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntoobs',
            name='id_punto_obs',
            field=models.CharField(help_text='AA, BB... para puntos no monumentalizados; P1, P2... para pilares', max_length=3, verbose_name='ID Punto de observación'),
        ),
    ]
