# Generated by Django 4.0.1 on 2022-11-28 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0054_alter_puntoobs_id_punto_obs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='puntoobs',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='puntoobs',
            name='estacion',
            field=models.ForeignKey(help_text='ID de la estación a la que pertenece el punto', on_delete=django.db.models.deletion.CASCADE, to='gravimetria.estacion'),
        ),
        migrations.AddConstraint(
            model_name='puntoobs',
            constraint=models.UniqueConstraint(fields=('estacion', 'id_punto_obs'), name='unique_punto_obs'),
        ),
    ]
