# Generated by Django 4.0.1 on 2022-11-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0055_alter_puntoobs_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntoobs',
            name='id_punto_obs',
            field=models.CharField(blank=True, default=None, help_text='AA, BB... para puntos no monumentalizados; P1, P2... para pilares', max_length=4, null=True, verbose_name='ID Punto de observación'),
        ),
    ]
