# Generated by Django 4.0.1 on 2022-12-22 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0058_alter_puntoobs_id_punto_obs_alter_puntoobs_latitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntoobs',
            name='altitud',
            field=models.FloatField(verbose_name='Altitud ortométrica [m]'),
        ),
        migrations.AlterField(
            model_name='puntoobs',
            name='longitud',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(limit_value=180, message='Introduzca un valor entre 180º y -180º'), django.core.validators.MinValueValidator(limit_value=-180, message='Introduzca un valor entre 180º y -180º')], verbose_name='Longitud [º]'),
        ),
    ]
