# Generated by Django 4.0.1 on 2022-12-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0059_alter_puntoobs_altitud_alter_puntoobs_longitud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puntoobs',
            options={'ordering': ['estacion__red_primaria', 'estacion', 'id_punto_obs'], 'verbose_name': 'punto de observación', 'verbose_name_plural': '\t\t\t\t\t\t\tPuntos de observación'},
        ),
    ]
