# Generated by Django 4.1.5 on 2023-02-01 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gravimetria', '0063_remove_observacion_new_punto_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='new_punto_obs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newpuntoobs', to='gravimetria.puntoobs'),
        ),
    ]
